name: Baseline Guard Test

on: [push]

jobs:
  baseline_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Baseline Guard
        uses: ./
        id: baseline
        with:
          target-baseline: "2023"
          scan-files: "**/*.js"    # changed to JS since you only have index.js
          fail-on-newly: "true"
      - name: Check Output
        run: echo "Violations found: ${{ steps.baseline.outputs.violations-found }}"