name: Baseline Guard Test

on: [push]

jobs:
  baseline_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Baseline Guard
        uses: ./   # This points to your action in this repo
        id: baseline
        with:
          target-baseline: '2023'
          scan-files: 'src/**/*.css'  # adjust to your repo
          fail-on-newly: 'true'
      - name: Check Output
        run: echo "Violations found: ${{ steps.baseline.outputs.violations-found }}"
