name: Baseline Guard Test

on: [push]

jobs:
  baseline_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Baseline Guard
        uses: ./ # This points to the action in the current repository
        id: baseline
        with:
          target-baseline: '2023'
          scan-files: 'src/**/*.css' # Adjust to your repository
          fail-on-newly: 'true'
      - name: Upload Report Artifact
        if: steps.baseline.outputs.violations-found == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.report-artifact-name || 'baseline-guard-report' }}
          path: baseline-guard-report.md
      - name: Check Output
        run: echo "Violations found:${{ steps.baseline.outputs.violations-found }}"
